### ISSUE TITLE
Error on running npm run typegen

### ISSUE THREAD

**Issue by darkwolf66** [7nohe/laravel-typegen#23]
Hey hey, this is personal project I haven't touch for a while, and now I'm getting this error when trying to run the command. Any idea what could be happening?
![image](https://github.com/7nohe/laravel-typegen/assets/2975858/883da890-bdb4-4a49-a704-44ce4c5fd30e)

**Comment by darkwolf66** [comment]
I downgraded to version 0.5.0 and it works again. Looks like that was made an upgrade on glob to a newer version without updating the code..

**Comment by 7nohe** [comment]
This has been resolved in v0.5.2.
