### ISSUE TITLE
Does it support ReactJS with inertia?

### ISSUE THREAD

**Issue by anburocky3** [7nohe/laravel-typegen#32]

**Comment by 7nohe** [comment]
@anburocky3 
Of course. While this library focuses on Inertia, it only provides TypeScript types, so it can also be used in a React (TypeScript) project with Inertia.

**Comment by anburocky3** [comment]
Proper example with reactjs would be super helpful. I was using Laravel Data for now to sync all the types. Your package looks cool. Will try it.

**Comment by 7nohe** [comment]
Thanks. I think there is also a demand for React, so I am considering adding an example.
Laravel Data is also a great library for synchronizing types too.
Laravel Typegen achieves type synchronization with an approach that does not require special modifications on the Laravel side.

**Comment by anburocky3** [comment]
I would defintely love it. Please give us a example. If you need any help on documentation, would like to help.
